name: Credentials
description: Configure AWS and PlanetScale Credentials

inputs:
  PLANETSCALE_TOKEN_ID:
    description: ''
    required: true
  PLANETSCALE_TOKEN:
    description: ''
    required: true

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::814320462898:role/iac
        aws-region: us-east-1

    - name: Authenticate on PlanetScale
      working-directory: .pscale/cli-helper-scripts
      shell: bash
      run: |
        . use-pscale-docker-image.sh
        pscale auth login --service-token-id ${{ inputs.PLANETSCALE_TOKEN_ID }} --service-token ${{ inputs.PLANETSCALE_TOKEN }}
