name: Create PlanetScale Branch Password

description: Create PlanetScale Branch Password and export it to SSM Parameter Store

inputs:
  db_name:
    required: true
    description: The Database Name
  org_name:
    required: true
    description: The Database Organization Name
  branch_name:
    required: true
    description: The Database Branch Name
  password_name:
    required: true
    description: The Database Password Name
    default: application

outputs:
  ID_PATH:
    value: ${{ steps.password.outputs.ID_PATH }}
    description: The ID Path
  URL_PATH:
    value: ${{ steps.password.outputs.URL_PATH }}
    description: The URL Path
  DATABASE_URL:
    value: ${{ steps.password.outputs.DATABASE_URL }}
    description: The Database URL

runs:
  using: 'composite'
  steps:
    - name: Create ${{ inputs.branch_name }} branch password if it does not exist
      shell: bash
      id: password
      working-directory: scripts/pscale
      env:
        DB_NAME: ${{ inputs.db_name }}
        ORG_NAME: ${{ inputs.org_name }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        PASSWORD_NAME: ${{ inputs.password_name }}
      run: |
        . functions.sh    

        URL_PATH="/pscale/$ORG_NAME/$DB_NAME/$BRANCH_NAME/$PASSWORD_NAME"
        DATABASE_URL=$(aws ssm get-parameters-by-path --path "$URL_PATH" --with-decryption --output json | jq -r ".Parameters[] | select(.Name == \"$URL_PATH\") | .Value")
        FOUND=$(pscale password list "$DB_NAME" "$BRANCH_NAME" --org "$ORG_NAME" --format json | jq -r ".[] | select(.name == \"$PASSWORD_NAME\") | .id")

        if [ -n "$DATABASE_URL" ] && [ -n "$FOUND" ]; then
          echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_OUTPUT
          echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV‘
          exit 0
        fi

        if [ ! -n "$DATABASE_URL" ] && [ -n "$FOUND" ]; then
          pscale password delete "$DB_NAME" "$BRANCH_NAME" "$FOUND" --org "$ORG_NAME" --force
        fi

        raw_db_url=$(pscale password create "$DB_NAME" "$BRANCH_NAME" "$PASSWORD_NAME" --org "$ORG_NAME" --format json)
        DATABASE_URL=$(echo "$raw_db_url" |  jq -r ". | \"mysql://\" + .username +  \":\" + .plain_text +  \"@\" + .database_branch.access_host_url + \"/$DB_NAME?ssl={\\\"rejectUnauthorized\\\":true}\"")
        aws ssm put-parameter --name "$URL_PATH" --value "$DATABASE_URL" --type SecureString --overwrite

        echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_OUTPUT
        echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV
