import { Article } from '@packages/client/src/components/Article'
import { Pages } from '@packages/client/src/components/Pages'
import styles from '@packages/client/src/styles/Home.module.css'
import { trpc } from '@packages/client/src/utils/trpc'
import { ZodPagination } from '@packages/server'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'

export default function FeedPage() {
  const router = useRouter()
  const pagination = ZodPagination.parse(router.query)
  const articlesQuery = trpc.articles.getFeed.useQuery({ pagination }).data

  return (
    <>
      <Head>
        <title>Realworld App!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={'/'}>Início</Link>
        <a href={'/feed'}>
          <h1>Feed</h1>
        </a>
        <ul>
          {articlesQuery &&
            articlesQuery.articles.map(article => (
              <li key={article.slug} className={styles.content}>
                <Article {...article} />
              </li>
            ))}
        </ul>
        {articlesQuery && <Pages pagination={pagination} totalInPage={articlesQuery.articles.length} />}
      </main>
    </>
  )
}
