import { Inter } from 'next/font/google'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { trpc } from '../utils/trpc'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const articles = trpc.articles.getMany.useQuery({ filters: {} })
  if (!articles.data) {
    return <div>Loading...</div>
  }
  return (
    <>
      <Head>
        <title>Main Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Realworld App!</h1>
        <ul>
          {articles.data.articles.map(article => (
            <li key={article.slug} className={styles.content}>
              <h2>
                <a href={`/articles/${article.slug}`}>{article.title}</a>
              </h2>
              <p>{article.description}</p>
              {article.favorited ?? <p>{article.favorited}</p>}
              <a href={`profiles/${article.author.username}`} target="_blank">
                <Image
                  src={article.author.image}
                  alt={'Author Profile'}
                  className={styles.vercelLogo}
                  width={100}
                  height={24}
                  target="_blank"
                />
              </a>
            </li>
          ))}
        </ul>
      </main>
    </>
  )
}
