name: Deploy

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate on PlanetScale
        working-directory: .pscale/cli-helper-scripts
        shell: bash
        run: |
          . use-pscale-docker-image.sh
          pscale auth login

      - uses: ./.github/actions/credentials

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4
          terraform_wrapper: false

      - uses: actions/download-artifact@v3
        with:
          name: build

      - id: paths
        uses: ./.github/actions/create_pscale_db_branch_password
        with:
          db_name: realworld-app
          org_name: santunioni
          branch_name: main

      - id: dburl
        shell: bash
        run: echo "DATABASE_URL=$(aws ssm get-parameter --name ${{ steps.paths.outputs.URL_PATH }} --with-decryption --query "Parameter.Value" --output text)" >> $GITHUB_OUTPUT

      - id: terraform
        run: make aws/terraform
        env:
          TF_VAR_DATABASE_URL: ${{ steps.dburl.outputs.DATABASE_URL }}
          TF_VAR_ENVIRONMENT: production
