name: Deploy

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/credentials
        with:
          PLANETSCALE_TOKEN_ID: ${{ secrets.PLANETSCALE_TOKEN_ID }}
          PLANETSCALE_TOKEN: ${{ secrets.PLANETSCALE_TOKEN }}

      - id: dburl
        uses: ./.github/actions/create_pscale_db_branch_password
        with:
          db_name: realworld-app
          org_name: santunioni
          branch_name: main

      - run: npm install
        shell: bash
        name: Dependencies

      - run: npm run migration:run
        shell: bash
        name: Migrations
        env:
          DATABASE_URL: ${{ steps.dburl.outputs.DATABASE_URL }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4
          terraform_wrapper: false

      - uses: actions/download-artifact@v3
        with:
          name: build

      - id: terraform
        run: make aws/terraform
        env:
          TF_VAR_DATABASE_URL: ${{ steps.dburl.outputs.DATABASE_URL }}
          TF_VAR_ENVIRONMENT: production
