name: Continuous Integration

run-name: Integration

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  DB_NAME: realworld-app
  ORG_NAME: santunioni
  PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_TOKEN_ID }}
  PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_TOKEN }}

jobs:
  checks:
    name: Checks

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: |
            package.json
            package-lock.json
            packages/*/package.json

      - run: npm install
        shell: bash
        name: Dependencies

      - name: Prettier
        run: npx prettier --check .

      - name: ESLint
        run: npm run lint --workspaces --if-present

      - name: Typescript
        run: npm run typecheck --workspaces --if-present

  server:
    name: Server Tests
    needs: checks
    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app
          MYSQL_USER: app
          MYSQL_PASSWORD: app
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql://app:app@localhost:3306/app
      API_BASE_URL: http://localhost:3000
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: |
            package.json
            package-lock.json
            packages/*/package.json

      - run: npm install
        shell: bash
        name: Dependencies

      - run: |
          npm run migration:run --workspace packages/server
          npm run migration:check --workspace packages/server
        shell: bash
        name: Migrations

      - run: npm run test --workspace packages/server
        shell: bash
        name: Server Unit Tests

      - name: Building Application
        shell: bash
        run: |
          npm run --workspace packages/server build:server

      - name: Starting localhost server
        shell: bash
        run: |
          nohup sh -c 'npm run build:server:start --workspace packages/server' &
          ./scripts/wait_for_status.sh http://localhost:3000/api/checks/readiness 200

      - run: npm run test --workspace packages/acceptance
        shell: bash
        name: Acceptance Tests

  lambda:
    name: Lambda Tests
    needs: checks

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: |
            package.json
            package-lock.json
            packages/*/package.json

      - uses: ./.github/actions/infrastructure # Will set the Env Vars at outputs /terraform/outputs.tf
        with:
          environment: ${{ inputs.environment }}

      - name: Dependencies
        shell: bash
        run: npm install

      - run: npm run migration:run --workspace packages/server
        shell: bash
        name: Migrations

      - name: Build
        shell: bash
        run: npm run build

      - name: Deploy
        shell: bash
        run: npm run deploy

      - name: Wait ${{ inputs.environment }}
        run: |
          ./scripts/wait_for_status.sh "$API_BASE_URL/api/checks/readiness" 200
          ./scripts/wait_for_status.sh "$API_BASE_URL/api/articles" 200

      - run: npm run test --workspace packages/acceptance
        shell: bash
        name: Acceptance Tests
