name: Clear Ephemeral Environments

run-name: Clear

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      continue-on-error:
        required: false
        type: boolean
        default: false

env:
  DB_NAME: realworld-app
  ORG_NAME: santunioni
  PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_TOKEN_ID }}
  PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_TOKEN }}
  environment: ephemeral-pr-${{ github.event.pull_request.number }}

concurrency:
  group: ${{ inputs.environment }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/credentials

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4
          terraform_wrapper: false

      - name: Clear Computing Resources
        continue-on-error: ${{ inputs.continue-on-error }}
        working-directory: packages/server/terraform
        run: |
          touch lambda.zip
          terraform init
          terraform workspace select ${{ inputs.environment }} || exit 0
          terraform refresh
          terraform destroy -auto-approve
          terraform workspace delete ${{ inputs.environment }}
        env:
          TF_VAR_DATABASE_URL: mysql://realworld-app:realworld-app@localhost:3306/realworld-app

  pscale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clear Database
        continue-on-error: ${{ inputs.continue-on-error }}
        working-directory: scripts/pscale
        run: |
          . functions.sh

          pscale branch delete $DB_NAME ${{ inputs.environment }} --org $ORG_NAME --force
