name: Clear Ephemeral Environments

run-name: Clear

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  DB_NAME: realworld-app
  ORG_NAME: santunioni
  PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_TOKEN_ID }}
  PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_TOKEN }}
  environment: ephemeral-pr-${{ github.event.pull_request.number }}

concurrency:
  group: ${{ inputs.environment }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/credentials

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4
          terraform_wrapper: false

      - name: Clear Ephemeral Environments
        continue-on-error: true
        working-directory: packages/server/terraform
        run: |
          terraform init -reconfigure -backend-config="key=realworld-app/$TF_VAR_ENVIRONMENT/lambda.tfstate"
          terraform refresh
          terraform destroy -auto-approve
        env:
          TF_VAR_ENVIRONMENT: ${{ inputs.environment }}

  pscale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Turn Down Database
        continue-on-error: true
        working-directory: .pscale/cli-helper-scripts
        run: |
          . use-pscale-docker-image.sh
          pscale branch delete $DB_NAME ${{ inputs.environment }} --org $ORG_NAME --force
