name: Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
    branches:
      - main

concurrency:
  group: pr-${{ github.ref }}

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
