name: Continuous Delivery Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: continuous-delivery-pipeline
  cancel-in-progress: false

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  sandbox:
    uses: ./.github/workflows/sandbox.yaml
    needs: [ci]

  cd:
    needs: [sandbox]
    uses: ./.github/workflows/cd.yaml
    secrets: inherit
