name: Continuous Delivery

run-name: Continuous Delivery

on:
  push:
    branches:
      - main

concurrency:
  group: continuous-delivery-pipeline
  cancel-in-progress: false

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
    name: Checks

  tests:
    uses: ./.github/workflows/unit.yaml
    needs: checks
    name: Unit

  sandbox:
    uses: ./.github/workflows/deploy.yaml
    name: Sandbox
    needs: checks
    secrets: inherit
    with:
      environment: sandbox

  acceptance:
    uses: ./.github/workflows/acceptance.yaml
    name: Acceptance
    needs: sandbox
    secrets: inherit
    with:
      API_BASE_URL: ${{ needs.sandbox.outputs.API_BASE_URL }}

  clear:
    needs: acceptance
    uses: ./.github/workflows/clear.yaml
    name: Clear
    secrets: inherit
    with:
      environment: sandbox

  cd:
    needs: [acceptance, tests]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    name: Production
    with:
      environment: main
