name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

  sandbox:
    uses: ./.github/workflows/sandbox.yaml
    if: github.event.pull_request.draft == false
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    needs: [ci]
    secrets: inherit
