name: Continuous Delivery

run-name: Continuous Delivery

on:
  push:
    branches:
      - main

concurrency:
  group: continuous-delivery-pipeline
  cancel-in-progress: false

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml

  tests:
    uses: ./.github/workflows/unit.yaml
    needs: checks

  sandbox:
    uses: ./.github/workflows/deploy.yaml
    name: Sandbox
    needs: checks
    secrets: inherit
    with:
      environment: sandbox

  clear:
    needs: sandbox
    uses: ./.github/workflows/clear.yaml
    secrets: inherit
    with:
      environment: sandbox

  cd:
    needs: [sandbox, tests]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      environment: main
