name: Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ephemeral-pr-${{ github.event.pull_request.number }}

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
    name: Checks

  tests:
    uses: ./.github/workflows/unit.yaml
    needs: checks
    name: Unit

  sandbox:
    uses: ./.github/workflows/deploy.yaml
    name: Sandbox
    secrets: inherit
    with:
      environment: pr${{ github.event.pull_request.number }}

  acceptance:
    uses: ./.github/workflows/acceptance.yaml
    name: Acceptance
    needs: sandbox
    secrets: inherit
    with:
      API_BASE_URL: ${{ needs.sandbox.outputs.API_BASE_URL }}
