name: Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ephemeral-pr-${{ github.event.pull_request.number }}

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml

  local-tests:
    uses: ./.github/workflows/local-tests.yaml
    needs: checks

  sandbox-deploy:
    uses: ./.github/workflows/deploy.yaml
    needs: checks
    secrets: inherit
    with:
      environment: sandbox

  sandbox-tests:
    uses: ./.github/workflows/acceptance-tests.yaml
    needs: sandbox-deploy
    secrets: inherit
    with:
      API_BASE_URL: ${{ needs.sandbox-deploy.outputs.API_BASE_URL }}
