name: Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ephemeral-pr-${{ github.event.pull_request.number }}

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml

  tests:
    uses: ./.github/workflows/unit.yaml
    needs: checks

  sandbox:
    uses: ./.github/workflows/deploy.yaml
    name: Sandbox
    needs: checks
    secrets: inherit
    with:
      environment: sandbox
