name: Continuous Delivery Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: continuous-delivery-pipeline
  cancel-in-progress: false

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  cd:
    needs: ci
    uses: ./.github/workflows/cd.yaml
    secrets: inherit
