name: Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ephemeral-pr-${{ github.event.pull_request.number }}

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      environment: ephemeral-pr-${{ github.event.pull_request.number }}
