name: Continuous Delivery

run-name: Continuous Delivery

on:
  push:
    branches:
      - main

concurrency:
  group: continuous-delivery-pipeline
  cancel-in-progress: false

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    with:
      environment: sandbox

  clear:
    needs: ci
    uses: ./.github/workflows/clear.yaml
    secrets: inherit
    with:
      environment: sandbox

  cd:
    needs: ci
    uses: ./.github/workflows/cd.yaml
    secrets: inherit
