name: On PR Closed

run-name: Destroying ephemeral-pr-${{ github.event.pull_request.number }}

on:
  pull_request:
    types: [closed]

jobs:
  clear:
    uses: ./.github/workflows/clear.yaml
    with:
      environment: ephemeral-pr-${{ github.event.pull_request.number }}
    secrets: inherit
