name: Continuous Delivery

run-name: Continuous Delivery

on:
  push:
    branches:
      - main

concurrency:
  group: continuous-delivery-pipeline
  cancel-in-progress: false

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml

  local-tests:
    uses: ./.github/workflows/local-tests.yaml
    needs: checks

  sandbox-deploy:
    uses: ./.github/workflows/deploy.yaml
    needs: checks
    secrets: inherit
    with:
      environment: sandbox

  sandbox-tests:
    uses: ./.github/workflows/acceptance-tests.yaml
    needs: sandbox-deploy
    secrets: inherit
    with:
      API_BASE_URL: jobs.sandbox-deploy.outputs.API_BASE_URL

  clear:
    needs: sandbox-tests
    uses: ./.github/workflows/clear.yaml
    secrets: inherit
    with:
      environment: sandbox

  cd:
    needs: [sandbox-tests, local-tests]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      environment: main
